name: nexus
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.1.1
  envied: ^0.3.0+3
  http: ^1.0.0
  flutter_tts: ^3.7.0
  permission_handler: ^10.3.0
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  envied_generator: ^0.3.0+3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - shorebird.yaml

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf